@extends('layouts.admin')

@section('content')
<div class="mb-8 flex justify-between items-end print:hidden">
    <div>
        <h1 class="text-2xl font-bold text-slate-800">Tax Invoices</h1>
        <p class="text-slate-500 text-sm">Track, search and audit unified taxpayer checkout invoices generated by online gateways.</p>
    </div>
</div>

<!-- Real-time Statistics Cards -->
@php
    $allInvoices = \App\Models\Invoice::get();
    $totalInvoiced = (float) $allInvoices->sum('total_amount');
    $totalSettled = (float) $allInvoices->where('status', 'success')->sum('total_amount');
    $pendingInvoicesCount = $allInvoices->where('status', 'pending')->count();
    $settleRate = $allInvoices->count() > 0 ? ($allInvoices->where('status', 'success')->count() / $allInvoices->count()) * 100 : 0;
@endphp
<div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
    <!-- Card 1: Total Invoiced -->
    <div class="bg-white rounded-[2.5rem] p-6 shadow-xl shadow-slate-200/50 border border-slate-100 relative overflow-hidden">
        <div class="absolute -right-4 -bottom-4 w-24 h-24 bg-primary-50 rounded-full blur-xl"></div>
        <div class="flex items-center justify-between mb-4">
            <div class="w-10 h-10 bg-primary-50 rounded-xl flex items-center justify-center text-primary-600 shrink-0">
                <i data-lucide="receipt" class="w-5 h-5"></i>
            </div>
            <span class="text-[10px] font-black text-primary-600 bg-primary-50 px-2 py-0.5 rounded-md uppercase tracking-wider">All time</span>
        </div>
        <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Total Invoiced</p>
        <h3 class="text-2xl font-black text-slate-800 mt-1">₦{{ number_format($totalInvoiced, 2) }}</h3>
    </div>

    <!-- Card 2: Total Settled -->
    <div class="bg-white rounded-[2.5rem] p-6 shadow-xl shadow-slate-200/50 border border-slate-100 relative overflow-hidden">
        <div class="absolute -right-4 -bottom-4 w-24 h-24 bg-emerald-50 rounded-full blur-xl"></div>
        <div class="flex items-center justify-between mb-4">
            <div class="w-10 h-10 bg-emerald-50 rounded-xl flex items-center justify-center text-emerald-600 shrink-0">
                <i data-lucide="check-circle" class="w-5 h-5"></i>
            </div>
            <span class="text-[10px] font-black text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-md uppercase tracking-wider">Success</span>
        </div>
        <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Total Settled</p>
        <h3 class="text-2xl font-black text-slate-800 mt-1">₦{{ number_format($totalSettled, 2) }}</h3>
    </div>

    <!-- Card 3: Pending Invoices -->
    <div class="bg-white rounded-[2.5rem] p-6 shadow-xl shadow-slate-200/50 border border-slate-100 relative overflow-hidden">
        <div class="absolute -right-4 -bottom-4 w-24 h-24 bg-amber-50 rounded-full blur-xl"></div>
        <div class="flex items-center justify-between mb-4">
            <div class="w-10 h-10 bg-amber-50 rounded-xl flex items-center justify-center text-amber-600 shrink-0">
                <i data-lucide="clock" class="w-5 h-5"></i>
            </div>
            <span class="text-[10px] font-black text-amber-600 bg-amber-50 px-2 py-0.5 rounded-md uppercase tracking-wider">Pending</span>
        </div>
        <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Pending Invoices</p>
        <h3 class="text-2xl font-black text-slate-800 mt-1">{{ number_format($pendingInvoicesCount) }}</h3>
    </div>

    <!-- Card 4: Settle Rate -->
    <div class="bg-white rounded-[2.5rem] p-6 shadow-xl shadow-slate-200/50 border border-slate-100 relative overflow-hidden">
        <div class="absolute -right-4 -bottom-4 w-24 h-24 bg-indigo-50 rounded-full blur-xl"></div>
        <div class="flex items-center justify-between mb-4">
            <div class="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-indigo-600 shrink-0">
                <i data-lucide="percent" class="w-5 h-5"></i>
            </div>
            <span class="text-[10px] font-black text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-md uppercase tracking-wider">Conversion</span>
        </div>
        <p class="text-[10px] font-black text-slate-400 uppercase tracking-widest">Settle Rate</p>
        <h3 class="text-2xl font-black text-slate-800 mt-1">{{ number_format($settleRate, 1) }}%</h3>
    </div>
</div>

<!-- Table & Filter Card -->
<div class="bg-white rounded-[2.5rem] shadow-xl shadow-slate-200/50 border border-slate-100 p-8">
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div>
            <h3 class="text-lg font-black text-slate-800">Invoices List</h3>
            <p class="text-xs text-slate-400">Search and monitor taxpayer checkout invoices references.</p>
        </div>

        <form action="{{ route('admin.invoices.index') }}" method="GET" class="flex flex-wrap items-center gap-3 print:hidden">
            <div class="relative w-56">
                <i data-lucide="search" class="w-4 h-4 text-slate-400 absolute left-4 top-3.5"></i>
                <input type="text" name="search" value="{{ request('search') }}" placeholder="Search Ref, Email, Est..." class="w-full pl-10 pr-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs focus:ring-4 focus:ring-primary-500/10 focus:border-primary-500 transition-all font-semibold">
            </div>

            <div class="w-48">
                <input type="text" name="date_range" value="{{ request('date_range') }}" placeholder="Select date range..." class="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs focus:ring-4 focus:ring-primary-500/10 focus:border-primary-500 transition-all font-semibold" id="dateRangePicker">
            </div>

            <select name="gateway" class="px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs focus:ring-4 focus:ring-primary-500/10 focus:border-primary-500 transition-all font-bold text-slate-600">
                <option value="">All Gateways</option>
                <option value="Paystack" {{ request('gateway') === 'Paystack' ? 'selected' : '' }}>Paystack</option>
                <option value="Monnify" {{ request('gateway') === 'Monnify' ? 'selected' : '' }}>Monnify</option>
            </select>

            <select name="status" class="px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs focus:ring-4 focus:ring-primary-500/10 focus:border-primary-500 transition-all font-bold text-slate-600">
                <option value="">All Statuses</option>
                <option value="pending" {{ request('status') === 'pending' ? 'selected' : '' }}>Pending</option>
                <option value="success" {{ request('status') === 'success' ? 'selected' : '' }}>Success</option>
                <option value="failed" {{ request('status') === 'failed' ? 'selected' : '' }}>Failed</option>
            </select>

            <button type="submit" class="px-5 py-2.5 bg-slate-800 text-white text-xs font-black uppercase tracking-widest rounded-xl hover:bg-slate-900 transition-all">Filter</button>
            @if(request()->anyFilled(['search', 'date_range', 'gateway', 'status']))
                <a href="{{ route('admin.invoices.index') }}" class="px-5 py-2.5 bg-slate-100 text-slate-600 text-xs font-black uppercase tracking-widest rounded-xl hover:bg-slate-200 transition-all font-bold">Clear</a>
            @endif
        </form>
    </div>

    <div class="overflow-x-auto">
        <table class="w-full">
            <thead>
                <tr class="border-b border-slate-100 text-left">
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Reference</th>
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Establishment</th>
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Taxpayer Email</th>
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Amount</th>
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Gateway</th>
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Date</th>
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Status</th>
                    <th class="pb-4 text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Actions</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-slate-50">
                @forelse($invoices as $invoice)
                    <tr class="group hover:bg-slate-50/50 transition-colors">
                        <td class="py-4 text-xs font-mono font-bold text-slate-700">{{ $invoice->reference }}</td>
                        <td class="py-4">
                            @if($invoice->establishment)
                                <a href="{{ route('admin.establishments.details', $invoice->establishment->id) }}" class="text-xs font-bold text-slate-800 hover:text-primary-600 transition-colors">
                                    {{ $invoice->establishment->name }}
                                </a>
                            @else
                                <span class="text-xs text-slate-400">Deleted Establishment</span>
                            @endif
                        </td>
                        <td class="py-4 text-xs text-slate-600">{{ $invoice->email }}</td>
                        <td class="py-4 text-xs font-black text-slate-800 text-right">₦{{ number_format($invoice->total_amount, 2) }}</td>
                        <td class="py-4">
                            @php
                                $gtColor = match($invoice->gateway) {
                                    'Paystack' => 'bg-orange-50 text-orange-600',
                                    'Monnify' => 'bg-purple-50 text-purple-600',
                                    default => 'bg-slate-50 text-slate-600',
                                };
                            @endphp
                            <span class="px-2.5 py-1 rounded-lg text-[9px] font-black uppercase tracking-wider {{ $gtColor }}">
                                {{ $invoice->gateway }}
                            </span>
                        </td>
                        <td class="py-4 text-xs font-medium text-slate-500">{{ $invoice->created_at->format('M d, Y h:ia') }}</td>
                        <td class="py-4">
                            @php
                                $statColor = match($invoice->status) {
                                    'success' => 'bg-emerald-100 text-emerald-700',
                                    'failed' => 'bg-rose-100 text-rose-700',
                                    default => 'bg-amber-100 text-amber-700',
                                };
                            @endphp
                            <span class="px-2.5 py-1 rounded-full text-[9px] font-black uppercase tracking-wider {{ $statColor }}">
                                {{ $invoice->status === 'success' ? 'Settled' : ucfirst($invoice->status) }}
                            </span>
                        </td>
                        <td class="py-4 text-center">
                            <a href="{{ route('admin.invoices.show', $invoice->id) }}" class="p-2 bg-slate-50 hover:bg-primary-50 rounded-xl inline-flex items-center text-slate-500 hover:text-primary-600 transition-all border border-slate-100 shadow-sm">
                                <i data-lucide="eye" class="w-4 h-4"></i>
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" class="py-12 flex flex-col items-center justify-center text-slate-400">
                            <i data-lucide="receipt" class="w-12 h-12 mb-4 opacity-20"></i>
                            <p class="text-sm font-bold uppercase tracking-widest">No invoice records found</p>
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="mt-8 print:hidden">
        {{ $invoices->links() }}
    </div>
</div>
@endsection

@push('styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<style>
    .flatpickr-calendar {
        border-radius: 1.5rem !important;
        box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1) !important;
        border: 1px solid rgba(241, 245, 249, 1) !important;
        font-family: inherit !important;
    }
    .flatpickr-day.selected {
        background: var(--primary-color) !important;
        border-color: var(--primary-color) !important;
    }
</style>
@endpush

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        flatpickr('#dateRangePicker', {
            mode: 'range',
            dateFormat: 'Y-m-d',
            maxDate: 'today',
            locale: {
                rangeSeparator: ' to '
            }
        });
    });
</script>
@endpush
