@extends('layouts.admin')

@section('title', 'Shop Allocations - Commercial Registry')

@section('content')
<div>
    <!-- Breadcrumb -->
    <div class="flex items-center text-xs font-semibold text-slate-500 mb-3 space-x-1.5 uppercase tracking-wider">
        <span>YSLG-IMRS</span>
        <i data-lucide="chevron-right" class="w-3.5 h-3.5 text-slate-400"></i>
        <span>Commercial registry</span>
        <i data-lucide="chevron-right" class="w-3.5 h-3.5 text-slate-400"></i>
        <span class="text-slate-900 font-bold">Shop allocations</span>
    </div>

    <!-- Page Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between pb-6 mb-6 border-b border-slate-200/80 gap-4">
        <div>
            <h1 class="text-2xl font-bold text-slate-900 tracking-tight">Shop allocations</h1>
            <p class="text-xs text-slate-500 mt-1 max-w-2xl leading-relaxed">
                Application through to allocation card. No unit is handed over until the invoice raised at approval has been paid.
            </p>
        </div>
        <div class="flex items-center flex-wrap gap-2.5">
            <a href="{{ route('public.shop-application.index') }}" target="_blank" class="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold rounded-lg shadow-sm transition-colors flex items-center gap-1.5">
                <i data-lucide="external-link" class="w-4 h-4"></i>
                Public application portal
            </a>
            @php
                $sampleCompleted = $allocations->where('stage', 7)->first();
            @endphp
            @if($sampleCompleted)
            <a href="{{ route('admin.allocations.card', $sampleCompleted) }}" class="px-4 py-2 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 text-xs font-semibold rounded-lg shadow-sm transition-colors flex items-center gap-1.5">
                <i data-lucide="badge-check" class="w-4 h-4 text-emerald-600"></i>
                Sample allocation card
            </a>
            @endif
            <a href="{{ route('admin.shops.index') }}" class="px-4 py-2 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 text-xs font-semibold rounded-lg shadow-sm transition-colors flex items-center gap-1.5">
                <i data-lucide="list" class="w-4 h-4 text-slate-500"></i>
                Shop inventory
            </a>
        </div>
    </div>

    <!-- Allocation Workflow Card (matching UI/index.html flow) -->
    <div class="bg-white border border-slate-200 rounded-xl p-6 shadow-sm mb-6">
        <div class="flex items-center justify-between mb-4">
            <h2 class="text-xs font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2">
                <i data-lucide="git-merge" class="w-4 h-4 text-emerald-600"></i>
                Allocation workflow architecture
            </h2>
            <span class="text-[11px] text-slate-400 font-semibold uppercase">7-Stage Regulatory Pipeline</span>
        </div>

        <!-- 7 Steps Stepper Horizontal -->
        <div class="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2.5">
            @php
                $stages = [
                    1 => ['title' => 'Application', 'desc' => 'Online submission'],
                    2 => ['title' => 'Review', 'desc' => 'Doc verification'],
                    3 => ['title' => 'Recommendation', 'desc' => 'Market Officer'],
                    4 => ['title' => 'Approval', 'desc' => 'Director Revenue'],
                    5 => ['title' => 'Allocation', 'desc' => 'Assign shop unit'],
                    6 => ['title' => 'Invoice & Pay', 'desc' => 'Rent & fee paid'],
                    7 => ['title' => 'Letter & Card', 'desc' => 'Handover certificate'],
                ];
            @endphp

            @foreach($stages as $stgNum => $stg)
            <div class="bg-slate-50 border border-slate-200 rounded-lg p-2.5 text-center relative">
                <div class="w-5 h-5 rounded-full bg-emerald-100 text-emerald-800 text-[10px] font-black flex items-center justify-center mx-auto mb-1 font-mono">
                    {{ $stgNum }}
                </div>
                <div class="text-[11px] font-bold text-slate-900 leading-tight">{{ $stg['title'] }}</div>
                <div class="text-[10px] text-slate-400 mt-0.5">{{ $stg['desc'] }}</div>
            </div>
            @endforeach
        </div>

        <p class="text-xs text-slate-500 mt-4 leading-relaxed">
            Applications are received and processed internally by the Market Officer and the Revenue Director. The allocation letter, certificate and card are generated by the system with a unique reference and a QR code.
        </p>
    </div>

    <!-- Applications Table Panel -->
    <div class="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden flex flex-col">
        <!-- Filter bar -->
        <div class="p-4 border-b border-slate-200 bg-slate-50/50 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div class="flex items-center gap-2">
                <h2 class="text-sm font-bold text-slate-900 uppercase tracking-wider">All Applications</h2>
                <span class="px-2 py-0.5 text-[10px] font-bold rounded-full bg-slate-100 text-slate-600">{{ $allocations->total() }} records</span>
            </div>

            <form method="GET" action="{{ route('admin.allocations.index') }}" class="flex flex-wrap items-center gap-2">
                <div class="relative w-48 sm:w-60">
                    <input type="text" name="search" value="{{ request('search') }}" placeholder="Reference, applicant, phone..." class="w-full text-xs rounded-lg border-slate-200 pl-8 pr-3 py-1.5 focus:ring-emerald-500 focus:border-emerald-500">
                    <i data-lucide="search" class="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-2.5"></i>
                </div>

                <select name="status" onchange="this.form.submit()" class="text-xs rounded-lg border-slate-200 py-1.5 focus:ring-emerald-500 focus:border-emerald-500">
                    <option value="">All Statuses</option>
                    <option value="pending" {{ request('status') === 'pending' ? 'selected' : '' }}>Pending</option>
                    <option value="review" {{ request('status') === 'review' ? 'selected' : '' }}>Review</option>
                    <option value="action_required" {{ request('status') === 'action_required' ? 'selected' : '' }}>Action Required</option>
                    <option value="approved" {{ request('status') === 'approved' ? 'selected' : '' }}>Approved</option>
                    <option value="completed" {{ request('status') === 'completed' ? 'selected' : '' }}>Completed / Allocated</option>
                    <option value="rejected" {{ request('status') === 'rejected' ? 'selected' : '' }}>Rejected</option>
                </select>
                <select name="market_id" onchange="this.form.submit()" class="text-xs rounded-lg border-slate-200 py-1.5 focus:ring-emerald-500 focus:border-emerald-500">
                    <option value="">All Markets</option>
                    @foreach($markets as $m)
                    <option value="{{ $m->id }}" {{ request('market_id') == $m->id ? 'selected' : '' }}>{{ $m->name }}</option>
                    @endforeach
                </select>

                @if(request()->anyFilled(['search', 'status', 'market_id', 'stage']))
                    <a href="{{ route('admin.allocations.index') }}" class="text-xs text-slate-500 hover:text-red-600 px-2 py-1">Reset</a>
                @endif
            </form>
        </div>

        <!-- Table matching UI/index.html lines 1434-1436 -->
        <div class="overflow-x-auto flex-1">
            <table class="w-full text-left text-xs">
                <thead class="bg-slate-50 text-slate-500 uppercase tracking-wider font-semibold border-b border-slate-200">
                    <tr>
                        <th class="py-3 px-4">Application</th>
                        <th class="py-3 px-4">Applicant</th>
                        <th class="py-3 px-4">Unit requested / Market</th>
                        <th class="py-3 px-3">Received</th>
                        <th class="py-3 px-3">Stage</th>
                        <th class="py-3 px-3 text-center">Status</th>
                        <th class="py-3 px-3 text-center">Action</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-100 text-slate-700">
                    @forelse($allocations as $alloc)
                    <tr class="hover:bg-slate-50/80 transition-colors group cursor-pointer" onclick="window.location='{{ route('admin.allocations.show', $alloc) }}'">
                        <td class="py-3 px-4 font-mono font-bold text-slate-900 group-hover:text-emerald-700 transition-colors">
                            {{ $alloc->application_no }}
                        </td>
                        <td class="py-3 px-4">
                            <div class="font-bold text-slate-900">{{ $alloc->applicant_name }}</div>
                            <div class="text-[11px] text-slate-400 font-medium">{{ $alloc->trade_type }} &middot; {{ $alloc->applicant_phone }}</div>
                        </td>
                        <td class="py-3 px-4">
                            @if($alloc->shop)
                                <span class="font-bold text-emerald-800">{{ $alloc->market->name }} &middot; {{ $alloc->shop->shop_number }}</span>
                                <div class="text-[11px] text-slate-400 font-mono">{{ $alloc->shop->shop_code }}</div>
                            @else
                                <span class="font-medium text-slate-800">{{ $alloc->market->name }}</span>
                                <div class="text-[11px] text-slate-400 font-italic">Unassigned unit ({{ $alloc->requested_size ?? 'Standard' }})</div>
                            @endif
                        </td>
                        <td class="py-3 px-3 font-mono text-slate-500">
                            {{ $alloc->created_at->format('d M Y') }}
                        </td>
                        <td class="py-3 px-3">
                            <div class="flex items-center gap-2">
                                <div class="w-16 bg-slate-100 rounded-full h-1.5 overflow-hidden">
                                    <div class="bg-emerald-600 h-1.5 rounded-full" style="width: {{ $alloc->stage_percentage }}%"></div>
                                </div>
                                <span class="font-mono text-[11px] font-semibold text-slate-700">{{ $alloc->stage }} of 7</span>
                            </div>
                        </td>
                        <td class="py-3 px-3 text-center">
                            @if($alloc->status === 'completed' || $alloc->stage === 7)
                                <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800">allocated</span>
                            @elseif($alloc->status === 'approved')
                                <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-blue-100 text-blue-800">approved</span>
                            @elseif($alloc->status === 'action_required')
                                <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-100 text-amber-900 border border-amber-300">Action Required</span>
                            @elseif($alloc->status === 'review' || $alloc->stage === 2 || $alloc->stage === 3)
                                <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-100 text-amber-800">review</span>
                            @elseif($alloc->status === 'rejected')
                                <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-red-100 text-red-800">rejected</span>
                            @else
                                <span class="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-slate-100 text-slate-600">{{ $alloc->status }}</span>
                            @endif
                        </td>
                        <td class="py-3 px-3 text-center" onclick="event.stopPropagation()">
                            <div class="flex items-center justify-center gap-1.5">
                                <a href="{{ route('admin.allocations.show', $alloc) }}" class="p-1 text-slate-400 hover:text-emerald-700" title="Review & Process">
                                    <i data-lucide="external-link" class="w-4 h-4"></i>
                                </a>
                                @if($alloc->stage === 7)
                                <a href="{{ route('admin.allocations.card', $alloc) }}" class="p-1 text-slate-400 hover:text-blue-700" title="View Allocation Card">
                                    <i data-lucide="badge-check" class="w-4 h-4 text-emerald-600"></i>
                                </a>
                                @endif
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" class="py-12 text-center text-slate-400">
                            No shop applications found matching the criteria.
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        @if($allocations->hasPages())
        <div class="p-4 border-t border-slate-200">
            {{ $allocations->links() }}
        </div>
        @endif
    </div>
</div>
@endsection
